- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80

  tasks:
  - name: Configure global attributes.
    fortios_firewall_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "60"
        hostname: "fg-tes"
