- hosts: all
  become: true

  tasks:
    - name: CP File clear-ram.sh 
      copy:
        src: /tmp/semaphore/repository_1_1/kagura/cron/clear-ram.sh
        dest: /home/hmi/clear-ram.sh
        mode: 0755
    - name: CLear RAM
      ansible.builtin.cron:
        name: Schedule Clear RAM
        minute: "*/60"
        user: root
        job: "/home/hmi/clear-ram.sh"
