- hosts: all
  become: true

  tasks:
    - name: CP File clear-ram.sh 
      copy:
        src: /kagura/cron/clear-ram.sh
        dest: /home/vaf/clear-ram.sh
        mode: 0755

    - name: CLear RAM
      command: sh /home/vaf/clear-ram.sh